//
//  HomeWorker.swift
//  ttb-Interview
//
//  Created by "" on 13/2/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class HomeWorker {
	func doSomeWork() {
	}
}
